# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - cerfa_nginx_data:/data
      - ./reverse_proxy/dev/includes:/etc/nginx/templates/includes/env

  ui:
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app #Allows source folders to be watched
      - /app/.next/
      - /app/node_modules/
    build:
      context: ui
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_ENV=dev
        - NEXT_PUBLIC_BASE_URL=http://localhost
        - NEXT_PUBLIC_BASE_HOST=localhost
        - NEXT_PUBLIC_METABASE_URL=https://contrat.apprentissage.beta.gouv.fr/
        - SKIP_PREFLIGHT_CHECK=true

  server:
    command: [ "yarn", "debug" ]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - cerfa_server_data:/data
      - ./server/agecap:/data/agecap
    environment:
      - CERFA_ENV=dev
      - CERFA_LOG_LEVEL=debug
      - CERFA_LOG_DESTINATIONS=stdout,mongodb
      - CERFA_SMTP_HOST=smtp
      - CERFA_SMTP_PORT=1025
    depends_on:
      - smtp

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - cerfa_mongodb_data:/data
  smtp:
    image: mailhog/mailhog
    container_name: cerfa_smtp
    mem_limit: 128m
    ports:
      - "1025:1025"
    networks:
      - cerfa_network
    environment:
      - MH_UI_WEB_PATH=smtp

  minio:
    image: minio/minio:latest
    container_name: cerfa_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin-user
      - MINIO_ROOT_PASSWORD=thisisapassword
    networks:
      - cerfa_network
    volumes:
      - ~/minio/data:/data
    restart: always

volumes:
  cerfa_mongodb_data:
    driver: local
    name: cerfa_mongodb_data
  cerfa_nginx_data:
    driver: local
    name: cerfa_nginx_data
  cerfa_server_data:
    driver: local
    name: cerfa_server_data
