version: "2.4"
services:

  waf:
    image: owasp/modsecurity-crs:3.3.2-nginx
    container_name: cerfa_waf
    ports:
      - 80:80
    depends_on:
      - reverse_proxy
    networks:
      - cerfa_network
    volumes:
      - ./waf/99-fix-resolver.sh:/docker-entrypoint.d/99-fix-resolver.sh:ro
      - ./waf/ws.inc:/etc/nginx/conf.d/ws.inc
    environment:
      - SERVERNAME=localhost
      - BLOCKING_PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - REPORTING_LEVEL=4
      - DNS_SERVER=127.0.0.11
      - PROXY=1
      - BACKEND=http://reverse_proxy
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT

  reverse_proxy:
    image: cerfa_reverse_proxy
    container_name: cerfa_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    networks:
      - cerfa_network
    depends_on:
      - server
      - ui

  ui:
    image: cerfa_ui
    container_name: cerfa_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - cerfa_network
    depends_on:
      - server
    environment:
      - SERVER_URI=http://reverse_proxy

  server:
    image: cerfa_server
    container_name: cerfa_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - cerfa_network
    depends_on:
      - mongodb
      - clamav
    environment:
      - CERFA_MONGODB_URI=mongodb://mongodb:27017/cerfa?retryWrites=true&w=majority
      - CERFA_LOG_DESTINATIONS=stdout,mongodb
      - CERFA_CLAMAV_URI=clamav:3310

  mongodb:
    image: mongo:5.0.6-focal
    container_name: cerfa_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - cerfa_network

  clamav:
    image: clamav/clamav:0.104.1
    container_name: cerfa_clamav
    restart: unless-stopped
    networks:
      - cerfa_network
    healthcheck:
      test: [ "CMD", "/usr/local/bin/clamdcheck.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s

networks:
  cerfa_network:
    name: cerfa_network
