version: "2.4"
services:
  reverse_proxy:
    image: cerfa_reverse_proxy
    container_name: cerfa_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - cerfa_network
    depends_on:
      - server
      - ui
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - REPORTING_LEVEL=4
      - DNS_SERVER=127.0.0.11
      - PROXY=1
      - SERVERNAME=localhost
      - ACCESSLOG=/data/access.log
      - ERRORLOG=/data/error.log
      - LOGLEVEL=warn
      - NGINX_ALWAYS_TLS_REDIRECT=false
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT

  ui:
    image: cerfa_ui
    container_name: cerfa_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - cerfa_network
    depends_on:
      - server
    environment:
      - SERVER_URI=http://reverse_proxy

  server:
    image: cerfa_server
    container_name: cerfa_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - cerfa_network
    depends_on:
      - mongodb
      - clamav
    environment:
      - CERFA_MONGODB_URI=mongodb://mongodb:27017/cerfa?retryWrites=true&w=majority
      - CERFA_LOG_DESTINATIONS=stdout,mongodb
      - CERFA_CLAMAV_URI=clamav:3310

  mongodb:
    image: mongo:5.0.6-focal
    container_name: cerfa_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - cerfa_network

  clamav:
    image: clamav/clamav:0.104.1
    container_name: cerfa_clamav
    restart: unless-stopped
    networks:
      - cerfa_network
    healthcheck:
      test: [ "CMD", "/usr/local/bin/clamdcheck.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s

networks:
  cerfa_network:
    name: cerfa_network
