version: "2.4"
services:

  crs:
    image: owasp/modsecurity-crs:3.3.2-nginx
    ports:
      - 80:80
      # only available if SETTLS was enabled:
      - 443:443
    depends_on:
      - reverse_proxy
    environment:
      - SERVERNAME=localhost
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4

      - REPORTING_LEVEL=2

      # Reverse Proxy mode
      - PROXY=1
      - BACKEND=http://reverse_proxy

    volumes:
      - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf


  reverse_proxy:
    image: cerfa_reverse_proxy
    container_name: cerfa_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - cerfa_network
    depends_on:
      - server
      - ui

  ui:
    image: cerfa_ui
    container_name: cerfa_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - cerfa_network
    depends_on:
      - server
    environment:
      - SERVER_URI=http://reverse_proxy

  server:
    image: cerfa_server
    container_name: cerfa_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - cerfa_network
    depends_on:
      - mongodb
      - clamav
    environment:
      - CERFA_MONGODB_URI=mongodb://mongodb:27017/cerfa?retryWrites=true&w=majority
      - CERFA_LOG_DESTINATIONS=stdout,mongodb
      - CERFA_CLAMAV_URI=clamav:3310

  mongodb:
    image: mongo:5.0.6-focal
    container_name: cerfa_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - cerfa_network

  clamav:
    image: clamav/clamav:0.104.1
    container_name: cerfa_clamav
    restart: unless-stopped
    networks:
      - cerfa_network
    healthcheck:
      test: [ "CMD", "/usr/local/bin/clamdcheck.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s

networks:
  cerfa_network:
    name: cerfa_network
