- name: Check if SSL certificate has been generated
  stat: path=/opt/cerfa/data/ssl/privkey.pem
  register: ssl

- name: Generate SSL certificate with LetsEncrypt
  shell: "bash /opt/cerfa/tools/ssl/generate-certificate.sh {{dns_name}}"
  register: output
  when: ssl.stat.exists == False

- debug:
    var: output
  when: ssl.stat.exists == True
