module.exports = [
  { code: "ALL", libelle: "Allée" },
  { code: "AV", libelle: "Avenue" },
  { code: "BD", libelle: "Boulevard" },
  { code: "CAR", libelle: "Carrefour" },
  { code: "CHE", libelle: "Chemin" },
  { code: "CHS", libelle: "Chaussée" },
  { code: "CITE", libelle: "Cité" },
  { code: "COR", libelle: "Corniche" },
  { code: "CRS", libelle: "Cours" },
  { code: "DOM", libelle: "Domaine" },
  { code: "DSC", libelle: "Descente" },
  { code: "ECA", libelle: "Ecart" },
  { code: "ESP", libelle: "Esplanade" },
  { code: "FG", libelle: "Faubourg" },
  { code: "GR", libelle: "Grande Rue" },
  { code: "HAM", libelle: "Hameau" },
  { code: "HLE", libelle: "Halle" },
  { code: "IMP", libelle: "Impasse" },
  { code: "LD", libelle: "Lieu-dit" },
  { code: "LOT", libelle: "Lotissement" },
  { code: "MAR", libelle: "Marché" },
  { code: "MTE", libelle: "Montée" },
  { code: "PAS", libelle: "Passage" },
  { code: "PL", libelle: "Place" },
  { code: "PLN", libelle: "Plaine" },
  { code: "PLT", libelle: "Plateau" },
  { code: "PRO", libelle: "Promenade" },
  { code: "PRV", libelle: "Parvis" },
  { code: "QUA", libelle: "Quartier" },
  { code: "QUAI", libelle: "Quai" },
  { code: "RES", libelle: "Résidence" },
  { code: "RLE", libelle: "Ruelle" },
  { code: "ROC", libelle: "Rocade" },
  { code: "RPT", libelle: "Rond-point" },
  { code: "RTE", libelle: "Route" },
  { code: "RUE", libelle: "Rue" },
  { code: "SEN", libelle: "Sente - Sentier" },
  { code: "SEN", libelle: "Sentier" },
  { code: "SQ", libelle: "Square" },
  { code: "TPL", libelle: "Terre-plein" },
  { code: "TRA", libelle: "Traverse" },
  { code: "VLA", libelle: "Villa" },
  { code: "VLGE", libelle: "Village" },
];
