version: "2.4"
services:
  server:
    environment:
      - CERFA_ENV=pentest
      - CERFA_LOG_LEVEL=info
      - CERFA_LOG_DESTINATIONS=stdout,mongodb
      - CERFA_PUBLIC_URL=https://contrat-pentest.apprentissage.beta.gouv.fr
      - CERFA_MONGODB_URI={{ vault[env_type].CERFA_MONGODB_URI }}
      - CERFA_TEAMS_WEBHOOK_URL={{ vault[env_type].CERFA_TEAMS_WEBHOOK_URL }}
      - CERFA_API_KEY={{ vault[env_type].CERFA_API_KEY }}
      - CERFA_AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].CERFA_AUTH_PASSWORD_HASH_ROUNDS }}
      - CERFA_AUTH_USER_JWT_SECRET={{ vault[env_type].CERFA_AUTH_USER_JWT_SECRET }}
      - CERFA_AUTH_PDS_JWT_SECRET={{ vault[env_type].CERFA_AUTH_PDS_JWT_SECRET }}
      - CERFA_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].CERFA_AUTH_ACTIVATION_JWT_SECRET }}
      - CERFA_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].CERFA_AUTH_PASSWORD_JWT_SECRET }}
      - CERFA_AUTH_YOUSIGN_WEBHOOK_JWT_SECRET={{ vault[env_type].CERFA_AUTH_YOUSIGN_WEBHOOK_JWT_SECRET }}
      - CERFA_SMTP_HOST={{ vault[env_type].CERFA_SMTP_HOST }}
      - CERFA_SMTP_PORT={{ vault[env_type].CERFA_SMTP_PORT }}
      - CERFA_OVH_STORAGE_URI={{ vault[env_type].CERFA_OVH_STORAGE_URI }}
      - CERFA_OVH_STORAGE_ENCRYPTION_KEY={{ vault[env_type].CERFA_OVH_STORAGE_ENCRYPTION_KEY }}
      - CERFA_API_ENTREPRISE_KEY={{ vault[env_type].CERFA_API_ENTREPRISE_KEY }}
      - CERFA_API_YOUSIGN_URL=https://staging-api.yousign.com
      - CERFA_API_YOUSIGN_KEY={{ vault[env_type].CERFA_API_YOUSIGN_KEY }}
      - CERFA_CLAMAV_URI=clamav:3310
      - CERFA_PDS_URL={{ vault[env_type].CERFA_PDS_URL }}
      - CERFA_PDS_CLIENT_ID={{ vault[env_type].CERFA_PDS_CLIENT_ID }}
      - CERFA_PDS_CLIENT_SECRET={{ vault[env_type].CERFA_PDS_CLIENT_SECRET }}
      - CERFA_IS_OFFLINE=false
      - CERFA_AGECAP_PASSPHRASE={{ vault[env_type].CERFA_AGECAP_PASSPHRASE }}
      - CERFA_API_AGECAP_URL={{ vault[env_type].CERFA_API_AGECAP_URL }}
      - CERFA_API_AGECAP_KEY={{ vault[env_type].CERFA_API_AGECAP_KEY }}
      - CERFA_STORAGE_TYPE={{ vault[env_type].CERFA_STORAGE_TYPE }}
      - CERFA_AWS_BUCKET_NAME={{ vault[env_type].CERFA_AWS_BUCKET_NAME }}
      - CERFA_AWS_BASE_PATH={{ vault[env_type].CERFA_AWS_BASE_PATH }}
      - CERFA_AWS_ACCESS_KEY_ID={{ vault[env_type].CERFA_AWS_ACCESS_KEY_ID }}
      - CERFA_AWS_SECRET_ACCES_KEY={{ vault[env_type].CERFA_AWS_SECRET_ACCES_KEY }}
      - CERFA_AWS_REGION={{ vault[env_type].CERFA_AWS_REGION }}

  ui:
      build:
        args:
          - NEXT_PUBLIC_ENV=pentest
          - NEXT_PUBLIC_BASE_URL=https://contrat-pentest.apprentissage.beta.gouv.fr
          - NEXT_PUBLIC_BASE_HOST=contrat-pentest.apprentissage.beta.gouv.fr
          - NEXT_PUBLIC_METABASE_URL=https://contrat-pentest.apprentissage.beta.gouv.fr

  metabase:
    environment:
      MB_SITE_URL: https://contrat-pentest.apprentissage.beta.gouv.fr/metabase

  smtp:
    image: mailhog/mailhog
    container_name: cerfa_smtp
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - cerfa_network
    environment:
      - MH_UI_WEB_PATH=smtp
      - MH_STORAGE=mongodb
      - MH_MONGO_URI=mongodb:27017
