#Override containers for azure environments
version: "2.4"
services:

  waf:
    ports:
      - 443:443
    depends_on:
      - reverse_proxy
    networks:
      - cerfa_network
    environment:
      - NGINX_ALWAYS_TLS_REDIRECT=on
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem
    volumes:
      - /opt/cerfa/data/ssl:/ssl:ro
      - /opt/cerfa/repository/waf/99-fix-resolver.sh:/docker-entrypoint.d/99-fix-resolver.sh:ro
      - /opt/cerfa/repository/waf/ws.inc:/etc/nginx/conf.d/ws.inc

  reverse_proxy:
    volumes:
      - /opt/cerfa/data/nginx:/data
      - /opt/cerfa/data/ssl:/ssl:ro
      - /opt/cerfa/.overrides/reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf:ro

  server:
    volumes:
      - /opt/cerfa/data/server:/data

  mongodb:
    command: mongod --auth
    volumes:
      - /opt/cerfa/data/mongodb/db:/data/db
      - /opt/cerfa/data/mongodb/configdb:/data/configdb
      - /opt/cerfa/data/mongodb/backups:/data/backups
      - /opt/cerfa/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "127.0.0.1:27017:27017"

  metabase:
    image: metabase/metabase:v0.42.0
    container_name: cerfa_metabase
    mem_limit: 2g
    volumes:
      - /opt/cerfa/data/metabase:/data/metabase
      - /opt/cerfa/backups/metabase:/data/backups
    depends_on:
      - mongodb
    environment:
      MB_DB_FILE: /data/metabase/metabase.db
      MB_SITE_LOCALE: fr
    restart: always
    networks:
      - cerfa_network
