name: Release version develop
on:
  push:
    branches: [ develop ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Run yarn Install
        run: yarn install

      - name: bump
        run: yarn npm:release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  deploy:
    needs: release
    # if: startsWith(github.event.ref, ‘refs/tags/’) != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - shell: bash
        run: echo '${{ github.head_ref }}  ${{ github.event.ref }} ${{ github.ref }}'
        
      - shell: bash 
        run: echo 'CERFA_HEAD_REF=${{ github.head_ref }}' >> $GITHUB_ENV

      - shell: bash
        run: echo 'CERFA_REF=${{ github.ref }}' >> $GITHUB_ENV

      - name: Check output
        run: echo ${CERFA_REF:-${CERFA_REF##*/}}

      - name: Request deployment recette
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mission-apprentissage/CERFA-infra
          token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
          event-type: deploy
          client-payload: '{"envName": "recette", "branchName":"develop"}'
        if: github.ref == 'refs/heads/develop'