name: Release version production
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Run yarn Install
        run: yarn install

      - name: bump
        run: yarn npm:release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  back-merge:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GH_TOKEN }}
  deploy:
    needs: release
    if: "!startsWith(github.event.head_commit.message, 'chore(release')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - shell: bash
        run: echo 'CERFA_HEAD_REF=${{ github.head_ref }}' >> $GITHUB_ENV

      - shell: bash
        run: echo 'CERFA_REF=${{ github.ref }}' >> $GITHUB_ENV

      - name: Check output
        run: echo ${CERFA_REF:-${CERFA_REF##*/}}

      - name: Request deployment production
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mission-apprentissage/CERFA-infra
          token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
          event-type: deploy
          client-payload: '{"envName": "production", "branchName":"main"}'
        if: github.ref == 'refs/heads/main'