name: Yarn CI Server
on: [ pull_request ]
jobs:
  ciserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      # Install dependencies
      - name: Run yarn Install
        run: yarn install

      # Install ui dependencies
      - name: Run yarn Install ui
        run: yarn --cwd ui install --frozen-lockfile

      # Install yarn dependencies
      - name: Run yarn Install server
        run: yarn --cwd server install --frozen-lockfile
      
      # Lint
      - name: Run Lint
        run: yarn lint

      # Start docker container for tests (e.g: mongodb)
      - name: Start Docker
        run: |
          yarn docker:start-ci

      # Run mocha tests
      - name: Run Tests
        run: |
          yarn --cwd server test:coverage

      # codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./server/coverage
          name: codecov-server
          verbose: true
      
      # Teardown
      - name: Teardown
        run: |
          yarn docker:down
